### PR TITLE
feat: todo

### PR DESCRIPTION
**Pull request by jazzcodes**
To-do list
- Add data
- Delete data
- Strike task
- Filter based on pending tasks

### CODE REVIEW

**Comment by mandeeps708** [comment]
If this PR contains all the code as `wip-dashboard-routing`, then we should point this PR to `wip-dashboard-routing` instead of master. Then this PR will only show the new changes.

**Comment by mandeeps708** [comment]
> If this PR contains all the code as `wip-dashboard-routing`, then we should point this PR to `wip-dashboard-routing` instead of master. Then this PR will only show the new changes.

Let me know when done. I will recheck the PR then.

**Comment by jazzcodes** [comment]
> 

changed the base 💯

**Comment by jazzcodes** [comment]
closing since changes since a lot has changed in PR #3

**Pull request closed without merging**
